### ISSUE TITLE
Add this greek channel

### ISSUE THREAD

**Issue by netmaxgr** [iptv-org/iptv#1026]
Hi,add this channel on greek category.It broadcasts movies/documentaries and some series

#EXTINF:-1,Netmax 
http://netmaxlive.tk:8080/hls/live/index.m3u8

**Comment by netmaxgr** [comment]
@freearhey

**Comment by freearhey** [comment]
Done.

**Comment by netmaxgr** [comment]
Hey @freearhey its not added on 

https://iptv-org.github.io/iptv/languages/el.m3u

**Comment by freearhey** [comment]
@netmaxgr for a channel to get into playlists sorted by language, you need to specify the correct `tvg-language` in its description. Here you can read how to do it: https://github.com/iptv-org/iptv/blob/master/.github/CONTRIBUTING.md#add-channel

**Comment by netmaxgr** [comment]
Done @freearhey 

#EXTINF:-1 tvg-id="Netmax" tvg-name="Netmax GR" tvg-language="Greek" tvg-logo="https://i.imgur.com/0sjticV.png" group-title="Movies",Netmax
http://netmaxlive.tk:8080/hls/live/index.m3u8

**Comment by netmaxgr** [comment]
@freearhey Sorry for the tag but my channel still isnt on 

https://iptv-org.github.io/iptv/countries/gr.m3u
and 


https://iptv-org.github.io/iptv/languages/el.m3u

**Comment by freearhey** [comment]
@netmaxgr It turned out that there was a syntax error in one of the files, so the playlists were not updated for several days. I have already fixed the bug and tomorrow everything should work out fine. 

Thank you for bringing this to my attention!
